#server.port=8001
#server.context-path=/hellospringboot
#mysql.jdbcDriverName=com.mysql.jdbc.Driver
#mysql.jdbcDriverUrl=jdbc:mysql://127.0.0.1:3306/system_dorm
#mysql.jdbcDriverUser=root
#mysql.jdbcDriverPassword=admincjb



#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/myweb?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=admincjb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


# http转到https密钥部分
#server.port=8443
#server.ssl.key-store=tomcat.keystore
#server.ssl.key-password=changeit
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=tomcat

server:
  port: 8443
  ssl:
    key-store: tomcat.keystore
    key-password: admincjb
    key-store-type: JKS
    key-alias: tomcat

#server:
#  port: 8001
#  context-path: /springboot
hellospringboot: Spring Boot开口测试

mysql: 
  jdbcName: com.mysql.jdbc.Driver
  dbUrl: jdbc:mysql://127.0.0.1:3306/myweb?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: admincjb
spring: 
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myweb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admincjb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


